name: cd-ghcr

on:
  push:
    branches: [master]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "*.md"
      - ".editorconfig"

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: network-tools

jobs:
  push:
    name: Push to GitHub container registry
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Run Shellcheck
        uses: azohra/shell-linter@latest

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into GitHub container registry ${{ env.REGISTRY }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: |
          REMOTE_IMAGE_NAME=${{ env.REGISTRY }}/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          REMOTE_IMAGE_NAME=$(echo $REMOTE_IMAGE_NAME | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo REMOTE_IMAGE_NAME=$REMOTE_IMAGE_NAME
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $REMOTE_IMAGE_NAME:$VERSION
          docker push $REMOTE_IMAGE_NAME:$VERSION
