name: cd-ghcr

on:
  # push:
  #   branches: [master]
  #   paths-ignore:
  #     - "*.md"
  #     - ".editorconfig"

  workflow_dispatch:

env:
  IMAGE_NAME: network-tools

jobs:
  push:
    name: Push to GitHub Container Registry
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to GitHub container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          # Only push if master/latest (for now)
          if [ "$VERSION" == "latest" ]; then
            docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION
          else
            echo "Push skipped, not on master branch, using latest tag."
            echo "IMAGE_NAME: $IMAGE_NAME"
            echo "IMAGE_ID:VERSION: $IMAGE_ID:$VERSION"
          fi
